name: CI Maven Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout del código
    - name: Checkout code
      uses: actions/checkout@v3

    # Configurar Java y Maven
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # Configurar las variables de entorno
    - name: Set environment variables
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI_READINGS }}
      run: echo "MONGODB_URI_READINGS is set"

    # Ejecutar Maven clean y package
    - name: Build with Maven
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI_READINGS }}
      run: mvn clean package -Dspring.data.mongodb.uri=${MONGODB_URI_READINGS}
